### ISSUE TITLE
Known issue:The add bot command doesnt work

### ISSUE THREAD

**Issue by iamashley0** [OpenBotlist/obl#10]
if you run the addbot cmnd,it returns this error:
ReferenceError: id is not defined 

see:[add-bot.js](https://github.com/OpenBotlist/obl/blob/master/src/commands/add-bot.js#L8)

**Comment by apenasigordev** [comment]
> if you run the addbot cmnd,it returns this error: ReferenceError: id is not defined
> 
> see:[add-bot.js](https://github.com/OpenBotlist/obl/blob/master/src/commands/add-bot.js#L8)

Try fix 😎

**Comment by TheAlan404** [comment]
im about to kill somebody

**Comment by TheAlan404** [comment]
@iamashley0 change L30
```diff
- id
+ bot.id
```
thats it.

**Comment by iamashley0** [comment]
fixed

**Comment by iamashley0** [comment]
> im about to kill somebody

plase dont
