### ISSUE TITLE
Skill Issue

### ISSUE THREAD

**Issue by link-discord** [OpenBotlist/obl#15]
This is a big issue

**Comment by apenasigordev** [comment]
i love front-end too :D

**Comment by iamashley0** [comment]
cntngjrkfnjkyrjhkfglbvc şnmtkhlfvb

**Comment by mustihavali** [comment]
guys obl logo = hole = phub refrnc?? 😨😨

**Comment by iamashley0** [comment]
> guys obl logo = hole = phub refrnc?? fearfulfearful

acutally its an onion ring lol

**Comment by link-discord** [comment]
Onion ring with Minecraft colors
